const enumConfig = {   
  
  EAbilTechPlayer: [],
  EAbilAlignment: [],
  EAcquireLevel: [],
  ECursorRangeMode: [],
  EAbilArmMagazineLaunch: [],
  EEffectLocationType: [],
  EAbilBehaviorCycleMode: [],
  EAbilBuildType: [],
  EAbilReviveVital: [],
  EDeathType: [],
  EAbilReviveCmd: [],
  EAbilOrderDisplayType: [],
  ECooldownLocation: [],
  ECooldownOperation: [],
  EChargeLocation: [],
  EAbilArmMagazineManage: [],
  EAbilCmdState: [],
  EAbilInventoryAlignment: [],
  EAbilMorphPhase: [],
  EAbilMorphSection: [],
  EAbilTrainLocation: [],
  EAbilTrainRotation: [],
  EUnitVital: [],
  ECargoSpace: [],
  EEffectAmount: [],
  EAccumulatorOperation: [],
  EAchievementTermEvaluate: [],
  EValueCompare: [],
  EAchievementTermPrevious: [],
  EAchievementTermCombine: [],
  EActorRequestCreateSharing: [],
  EActorHostedPropInheritType: [],
  EActorScopeBearingsTrackingType: [],
  EFogVisibility: [],
  EActorSplatHeight: [],
  EActorProximity: [],
  EActorModelMaterialType: [],
  EActorSoundPlayMode: [],
  ESplatLayer: [],
  EActorEffectScope: [],
  EActorShieldFlashType: [],
  EMinimapShape: [],
  ESquibType: [],
  EActorSiteBillboardType: [],
  EActorSiteOrbiterType: [],
  EActorSiteOpActionLocation: [],
  EActorSiteOpAttachSource: [],
  EActorSiteOpBasicType: [],
  EActorEffectLocation: [],
  EActorHeightSourceType: [],
  EActorIncomingType: [],
  EActorSiteOpOrientAttachPointToType: [],
  EActorRadialDistribution: [],
  EActorSiteOpPhysicsImpactType: [],
  EActorCrossbarDistribution: [],
  EActorSiteOpRotatorType: [],
  EActorHeightTestType: [],
  EActorTiltType: [],
  EActorTextAlignment: [],
  EAttachmentID: [],
  EUnitSound: [],
  EAlertPeripheral: [],
  EArmyCategoryState: [],
  EArmyUnitState: [],
  EArmyUpgradeState: [],
  EAMArcTestType: [],
  EAMFilterLogic: [],
  EAMFilterAttachType: [],
  EAMFilterType: [],
  EAMAttachType: [],
  EAMOccupancyLogic: [],
  EAMNumericField: [],
  EAMNumericFieldOp: [],
  EAMPatternType: [],
  EAttachKeyword: [],
  EAMRandomDistribution: [],
  EAMReductionType: [],
  EBankConditionCombine: [],
  EBehaviorAlignment: [],
  EBehaviorBuffReplace: [],
  EAllianceId: [],
  ECameraHeightMap: [],
  ECharacterGender: [],
  ECharacterRace: [],
  ECharacterRelevance: [],
  EConversationProductionLevel: [],
  EGameCatalog: [],
  EImplementionLevel: [],
  EOscillator: [],
  EEffectHistory: [],
  EHeightMap: [],
  EListWalkMode: [],
  EDamageVisibility: [],
  EDamageKind: [],
  EDamageType: [],
  EDamageTotal: [],
  EMoverPatternType: [],
  EClassIdCBehavior: [],
  EEffectRemoveBehaviorAlignment: [],
  EBehaviorHeroicState: [],
  EUpgradeOperation: [],
  EUIColorRelation: [],
  EGlueTheme: [],
  EHeroState: [],
  EPurchaseWarningCondition: [],
  EHeroAbilState: [],
  EEffectLocation: [],
  EEffectPlayer: [],
  EMapKind: [],
  EOcclusion: [],
  EPausedParticleSystemBehavior: [],
  EFoliageLayer: [],
  EPathMode: [],
  EObjectiveType: [],
  EDamageLocation: [],
  EResponseContinueMethod: [],
  EDamageResponseDamageValue: [],
  EPreloadTiming: [],
  EScoreSort: [],
  EScoreValueReport: [],
  EScoreCollapse: [],
  EScoreValueType: [],
  EScoreValue: [],
  EScoreValueOperation: [],
  ESoundCategory: [],
  ESoundBlend: [],
  ESoundDupe: [],
  ESoundMode: [],
  ESoundSelect: [],
  EExclusivityAction: [],
  EExclusivityQueueAction: [],
  EUnitAttribute: [],
  ETargetFindSet: [],
  ETurretIdle: [],
  EDeathReveal: [],
  EUnitMob: [],
  EUnitGender: [],
  EResourceState: [],
  EResourceType: [],
  EUnitResponse: [],
  EArmorType: [],
  ECostCategory: [],
  EKillDisplay: [],
  ERankDisplay: [],
  EUserType: [],
  EEditorTextType: [],
  ETextTagEdge: [],
  EValidateCombine: [],
  EGameResult: [],
  EPlayerType: [],
  EUnitAIFlag: [],
  EAlliancePlayer: [],
  EClassIdCAbil: [],
  EBehaviorState: [],
  EUnitTestState: [],
  EPlayerRelationship: [],
  EUnitType: [],
  EPlane: [],
  EWeaponType: [],
  EVitalType: [],
  EWeaponPrioritization: [],
  EWeaponLegacyMovement: [],
  EEffectUnit: [],
  EAchievementTagCheck: [],
  EActorRequestScope: [],
  EActorRequestActor: [],
  EActorModelAspectPerson: [],
  EActorModelAspectObservingPoV: [],
  EActorModelAspectRegardsAs: [],
  EActorModelAspectDuring: [],
  EActorModelAspectObservedPlayerType: [],
  EActorModelAspectModelOwnerType: [],
  EActorModelAspectTest: [],
  EActorPhysicsImpactRangeType: [],
  EActorQuadDecorationFunction: [],
  EActorSoundValueSource: [],
  EActorResponseScope: [],
  EActorIntersectType: [],
  EActorAnimTransitionType: [],
  EActorAnimPropMatchType: [],
  ESerpentType: [],
  ECmdResult: [],
  EEffectTimeScale: [],
  EDamageResponseHandledValue: [],
  EConversationConditionOp: [],
  EConversationActionOp: [],
  EConversationConditionCheck: [],
  EConversationSelectionMethod: [],
  EEffectModifyTurret: [],
  EFootprintShapeMode: [],
  EDamageCategory: [],
  ESoundFormat: [],
  ESoundResampler: [],
  ESpeakerMode: [],
  EMuteControl: [],
  EVolumeControl: [],
  ESoundMaxMethod: [],
  EGameCategoryUsage: [],
  EHeroAbilCategoryState: [],
  EHeroAITalentBuildType: [],
  EHeroStatState: [],
  EVariationCommands: [],
  ETonemapRegionTypes: [],
  EMissionState: [],
  EModelEvent: [],
  EModelQuality: [],
  EPhysicsMaterial: [],
  EMotionDriverType: [],
  EMotionTurnType: [],
  EMotionActorTrackingType: [],
  EMotionArrivalTestType: [],
  EMotionBlendType: [],
  EMotionRotationLaunchActorType: [],
  EMotionRotationActorType: [],
  EMotionThrowRotationType: [],
  EMotionOverlayType: [],
  EMotionOverlayPolarity: [],
  ERequirementState: [],
  ECardButtonType: [],
  EVoiceOverSkinState: [],
  EVoiceOverSoundType: [],
  ETalentModification: [],
  ESoundMaxPrioritization: [],
  EActorOverkillTestType: [],
  ECommanderTalentType: [],
  ECommanderMasteryTalentType: [],
  EGameTimeEvent: [],
  ESkillPoint: [],
  EAbilEffectStage: [],
  ESoundDupePriority: [],
  EKineticFollow: [],
  ETargetModeValidation: [],
  EQuickCastMode: [],
  EHerdClosestTo: [],
  EHeroRole: [],
  EHeroImageFacing: [],
  EHeroCutsceneSize: [],
  EHeroDifficulty: [],
  EHeroGender: [],
  EAttackType: [],
  EEffectContainer: [],
  EEffectModifyFacing: [],
  EBehaviorUnitTrackerAtMaxRule: [],
  EBehaviorUnitTrackerSnapRule: [],
  EArtifactType: [],
  EHeroUniverse: [],
  EActorForceOrigin: [],
  EActorCombatRevealDurationType: [],
  EActorForceField: [],
  EAbilLastTarget: [],
  EAccumulatorApplicationRule: [],
  EVitalsAccumulatorModificationType: [],
  EAccumulatorBehaviorType: [],
  EActorPlayerIdSource: [],
  EActorForceDirection: [],
  EActorSiteOpTetherEnableType: [],


  EClassIdCAbil: [
    "CAbil",
    "CAbilProgress",
    "CAbilEffect",
    "CAbilQueueable",
    "CAbilRedirect",
    "CAbilArmMagazine",
    "CAbilAttack",
    "CAbilAugment",
    "CAbilAttackModifier",
    "CAbilBattery",
    "CAbilBeacon",
    "CAbilBehavior",
    "CAbilBuild",
    "CAbilBuildable",
    "CAbilEffectInstant",
    "CAbilEffectTarget",
    "CAbilHarvest",
    "CAbilInteract",
    "CAbilInventory",
    "CAbilLearn",
    "CAbilMerge",
    "CAbilMergeable",
    "CAbilMorph",
    "CAbilMorphPlacement",
    "CAbilMove",
    "CAbilPawn",
    "CAbilQueue",
    "CAbilRally",
    "CAbilRedirectInstant",
    "CAbilRedirectTarget",
    "CAbilResearch",
    "CAbilRevive",
    "CAbilSpecialize",
    "CAbilStop",
    "CAbilTrain",
    "CAbilTransport",
    "CAbilWarpable",
    "CAbilWarpTrain"
  ],
  EAbilAttackStage: [
    "Approach",
    "Attack",
    "Loiter"
  ],
  EAbilBehaviorStage: [
    "Untoggled",
    "Toggled"
  ],
  EAbilBuildStage: [
    "Approach",
    "Wait",
    "Construct",
    "Halt",
    "Resume",
    "Finish",
    "Collide"
  ],
  EAbilEffectStage: [
    "Approach",
    "Wait",
    "Prep",
    "Cast",
    "Channel",
    "Finish",
    "Bail"
  ],
  EAbilHarvestStage: [
    "ApproachResource",
    "WaitAtResource",
    "Harvest",
    "WaitToReturn",
    "WaitForDropOff",
    "ApproachDropOff",
    "DropOff"
  ],
  EAbilMorphStage: [
    "Approach",
    "Wait",
    "AbilsStart",
    "AbilsEnd",
    "ActorStart",
    "ActorEnd",
    "CollideStart",
    "CollideEnd",
    "FacingStart",
    "FacingEnd",
    "MoverStart",
    "MoverEnd",
    "StatsStart",
    "StatsEnd",
    "UnitStart",
    "UnitEnd"
  ],
  EAbilRallyStage: [
    "Place"
  ],
  EAbilArmMagazineCmd: [
    "Ammo1",
    "Ammo2",
    "Ammo3",
    "Ammo4",
    "Ammo5",
    "Ammo6",
    "Ammo7",
    "Ammo8",
    "Ammo9",
    "Ammo10",
    "Ammo11",
    "Ammo12",
    "Ammo13",
    "Ammo14",
    "Ammo15",
    "Ammo16",
    "Ammo17",
    "Ammo18",
    "Ammo19",
    "Ammo20"
  ],
  EAbilAttackCmd: [
    "Execute",
    "Towards",
    "Barrage"
  ],
  EAbilAttackModifierCmd: [
    "Execute"
  ],
  EAbilAugmentCmd: [
    "Execute"
  ],
  EAbilBatteryCmd: [
    "Execute"
  ],
  EAbilBeaconCmd: [
    "Cancel",
    "Move"
  ],
  EAbilBehaviorCmd: [
    "On",
    "Off"
  ],
  EAbilBuildCmd: [
    "Build1",
    "Build2",
    "Build3",
    "Build4",
    "Build5",
    "Build6",
    "Build7",
    "Build8",
    "Build9",
    "Build10",
    "Build11",
    "Build12",
    "Build13",
    "Build14",
    "Build15",
    "Build16",
    "Build17",
    "Build18",
    "Build19",
    "Build20",
    "Build21",
    "Build22",
    "Build23",
    "Build24",
    "Build25",
    "Build26",
    "Build27",
    "Build28",
    "Build29",
    "Build30",
    "Halt"
  ],
  EAbilBuildableCmd: [
    "Cancel",
    "Halt"
  ],
  EAbilEffectInstantCmd: [
    "Execute",
    "Cancel"
  ],
  EAbilEffectTargetCmd: [
    "Execute",
    "Cancel"
  ],
  EAbilHarvestCmd: [
    "Gather",
    "Return",
    "Cancel"
  ],
  EAbilInteractCmd: [
    "Designate"
  ],
  EAbilInventoryCmd: [
    "Drop",
    "Move",
    "Take",
    "ItemInstant",
    "ItemTarget",
    "ItemCancel",
    "PawnInstant",
    "ItemTogOn",
    "ItemTogOff"
  ],
  EAbilLearnCmd: [
    "Learn1",
    "Learn2",
    "Learn3",
    "Learn4",
    "Learn5",
    "Learn6",
    "Learn7",
    "Learn8",
    "Learn9",
    "Learn10",
    "Learn11",
    "Learn12",
    "Learn13",
    "Learn14",
    "Learn15",
    "Learn16",
    "Learn17",
    "Learn18",
    "Learn19",
    "Learn20"
  ],
  EAbilMergeCmd: [
    "SelectedUnits",
    "WithTarget"
  ],
  EAbilMorphCmd: [
    "Execute",
    "Cancel",
    "Unmorph"
  ],
  EAbilMergeableCmd: [
    "Cancel"
  ],
  EAbilMoveCmd: [
    "Move",
    "Patrol",
    "HoldPos",
    "AcquireMove",
    "Turn"
  ],
  EAbilPawnCmd: [
    "Pawn1",
    "Pawn2",
    "Pawn3",
    "Pawn4",
    "Pawn5",
    "Pawn6",
    "Pawn7",
    "Pawn8",
    "Pawn9",
    "Pawn10",
    "Pawn11",
    "Pawn12",
    "Pawn13",
    "Pawn14",
    "Pawn15",
    "Pawn16",
    "Pawn17",
    "Pawn18",
    "Pawn19",
    "Pawn20"
  ],
  EAbilQueueCmd: [
    "CancelLast",
    "CancelSlot"
  ],
  EAbilRallyCmd: [
    "Rally1",
    "Rally2",
    "Rally3",
    "Rally4"
  ],
  EAbilRedirectInstantCmd: [
    "Execute"
  ],
  EAbilRedirectTargetCmd: [
    "Execute"
  ],
  EAbilResearchCmd: [
    "Research1",
    "Research2",
    "Research3",
    "Research4",
    "Research5",
    "Research6",
    "Research7",
    "Research8",
    "Research9",
    "Research10",
    "Research11",
    "Research12",
    "Research13",
    "Research14",
    "Research15",
    "Research16",
    "Research17",
    "Research18",
    "Research19",
    "Research20",
    "Research21",
    "Research22",
    "Research23",
    "Research24",
    "Research25",
    "Research26",
    "Research27",
    "Research28",
    "Research29",
    "Research30"
  ],
  EAbilReviveCmd: [
    "Revive1",
    "Revive2",
    "Revive3",
    "Revive4",
    "Revive5",
    "Revive6",
    "Revive7",
    "Revive8",
    "Revive9",
    "Revive10",
    "Revive11",
    "Revive12",
    "Revive13",
    "Revive14",
    "Revive15",
    "Revive16",
    "Revive17",
    "Revive18",
    "Revive19",
    "Revive20",
    "ReviveAtTarget1",
    "ReviveAtTarget2",
    "ReviveAtTarget3",
    "ReviveAtTarget4",
    "ReviveAtTarget5",
    "ReviveAtTarget6",
    "ReviveAtTarget7",
    "ReviveAtTarget8",
    "ReviveAtTarget9",
    "ReviveAtTarget10"
  ],
  EAbilSpecializeCmd: [
    "Specialize1",
    "Specialize2",
    "Specialize3",
    "Specialize4",
    "Specialize5",
    "Specialize6",
    "Specialize7",
    "Specialize8",
    "Specialize9",
    "Specialize10",
    "Specialize11",
    "Specialize12",
    "Specialize13",
    "Specialize14",
    "Specialize15",
    "Specialize16",
    "Specialize17",
    "Specialize18",
    "Specialize19",
    "Specialize20"
  ],
  EAbilStopCmd: [
    "Stop",
    "HoldFire",
    "Cheer",
    "Dance",
    "Tease",
    "RequestPickup"
  ],
  EAbilTrainCmd: [
    "Train1",
    "Train2",
    "Train3",
    "Train4",
    "Train5",
    "Train6",
    "Train7",
    "Train8",
    "Train9",
    "Train10",
    "Train11",
    "Train12",
    "Train13",
    "Train14",
    "Train15",
    "Train16",
    "Train17",
    "Train18",
    "Train19",
    "Train20",
    "Train21",
    "Train22",
    "Train23",
    "Train24",
    "Train25",
    "Train26",
    "Train27",
    "Train28",
    "Train29",
    "Train30"
  ],
  EAbilTransportCmd: [
    "Load",
    "UnloadAll",
    "UnloadAt",
    "UnloadUnit",
    "LoadAll"
  ],
  EAbilWarpableCmd: [
    "Cancel"
  ],
  EAbilWarpTrainCmd: [
    "Train1",
    "Train2",
    "Train3",
    "Train4",
    "Train5",
    "Train6",
    "Train7",
    "Train8",
    "Train9",
    "Train10",
    "Train11",
    "Train12",
    "Train13",
    "Train14",
    "Train15",
    "Train16",
    "Train17",
    "Train18",
    "Train19",
    "Train20"
  ],
  EAbilityCategory: [
    "User1",
    "User2",
    "User3",
    "User4",
    "User5",
    "Magic",
    "Physical",
    "Aura",
    "Passive",
    "Dispel",
    "PassivePhysical",
    "PassiveMagic",
    "Heal",
    "SpellSteal",
    "Repair",
    "Polymorph",
    "BlockByMorph",
    "Ultimate",
    "CanBeDisabled",
    "CanBeSilenced",
    "CanBeIllusionDisabled"
  ],
  EClassIdCAccumulator: [
    "CAccumulator",
    "CAccumulatorConstant",
    "CAccumulatorVitals",
    "CAccumulatorDistance",
    "CAccumulatorBehavior",
    "CAccumulatorAttributePoints",
    "CAccumulatorTrackedUnitCount",
    "CAccumulatorLevel",
    "CAccumulatorAbilLevel",
    "CAccumulatorUnitLevel",
    "CAccumulatorVeterancyLevel",
    "CAccumulatorCargo",
    "CAccumulatorEffectAmount",
    "CAccumulatorUserData",
    "CAccumulatorUnitCustomValue",
    "CAccumulatorSwitch",
    "CAccumulatorArithmetic",
    "CAccumulatorPlayerScoreValue"
  ],
  EClassIdCAchievement: [
    "CAchievement"
  ],
  EClassIdCAchievementTerm: [
    "CAchievementTerm",
    "CAchievementTermAbil",
    "CAchievementTermAbilInteract",
    "CAchievementTermAbilLoad",
    "CAchievementTermAbilUse",
    "CAchievementTermAchievement",
    "CAchievementTermBehavior",
    "CAchievementTermBehaviorAbsorbed",
    "CAchievementTermBehaviorCount",
    "CAchievementTermBehaviorElapsed",
    "CAchievementTermBehaviorState",
    "CAchievementTermCombine",
    "CAchievementTermEffect",
    "CAchievementTermEffectAbsorbed",
    "CAchievementTermEffectDamaged",
    "CAchievementTermEffectDodged",
    "CAchievementTermEffectHealed",
    "CAchievementTermEffectKilled",
    "CAchievementTermEffectUse",
    "CAchievementTermGeneric",
    "CAchievementTermReplay",
    "CAchievementTermScoreValue",
    "CAchievementTermTime",
    "CAchievementTermUnit",
    "CAchievementTermUnitBirth",
    "CAchievementTermUnitDeath",
    "CAchievementTermUnitKills",
    "CAchievementTermUnitRegen",
    "CAchievementTermUnitSupplyLoss"
  ],
  EClassIdCActor: [
    "CActor",
    "CActorBase",
    "CActorBearings",
    "CActorCamera",
    "CActorModel",
    "CActorModelMaterial",
    "CActorQuad",
    "CActorForce",
    "CActorForceLineSegment",
    "CActorBeam",
    "CActorRange",
    "CActorRegion",
    "CActorSite",
    "CActorSiteOp",
    "CActorSiteOpBase",
    "CActorSound",
    "CActorSplat",
    "CActorAction",
    "CActorActionOverride",
    "CActorArc",
    "CActorBeamSimple",
    "CActorBeamStandard",
    "CActorBlob",
    "CActorCameraModel",
    "CActorCreep",
    "CActorCutscene",
    "CActorDoodad",
    "CActorDoodadPreserver",
    "CActorFoliageFXSpawner",
    "CActorEditorCamera",
    "CActorEditorPoint",
    "CActorEventMacro",
    "CActorEventMacroRunnable",
    "CActorForceBox",
    "CActorForceConeRoundedEnd",
    "CActorForceCylinder",
    "CActorForceSphere",
    "CActorGlobalConfig",
    "CActorOverrides",
    "CActorLight",
    "CActorLightOmni",
    "CActorLightSpot",
    "CActorLightModel",
    "CActorLightOmniModel",
    "CActorLightSpotModel",
    "CActorLookAt",
    "CActorList",
    "CActorListPerPlayer",
    "CActorPortrait",
    "CActorPower",
    "CActorProgress",
    "CActorPropertyCurveSet",
    "CActorQueryResponse",
    "CActorRegionArc",
    "CActorRegionCircle",
    "CActorRegionCombine",
    "CActorRegionGame",
    "CActorRegionPolygon",
    "CActorRegionQuad",
    "CActorRegionWater",
    "CActorScene",
    "CActorSelection",
    "CActorSetQueried",
    "CActorShadow",
    "CActorShield",
    "CActorShieldImpact",
    "CActorSimple",
    "CActorSiteBillboard",
    "CActorSiteMover",
    "CActorSiteOrbiter",
    "CActorSiteRocker",
    "CActorSiteOp2DRotation",
    "CActorSiteOpAction",
    "CActorSiteOpAttach",
    "CActorSiteOpAttachVolume",
    "CActorSiteOpBanker",
    "CActorSiteOpBankerUnit",
    "CActorSiteOpBasic",
    "CActorSiteOpGameCameraFollow",
    "CActorSiteOpDeathMotion",
    "CActorSiteOpDeltaSum",
    "CActorSiteOpEffect",
    "CActorSiteOpForward",
    "CActorSiteOpHeight",
    "CActorSiteOpHigherOfTerrainAndWater",
    "CActorSiteOpHostBearings",
    "CActorSiteOpHostedOffset",
    "CActorSiteOpIncoming",
    "CActorSiteOpLocalOffset",
    "CActorSiteOpOrientAttachPointTo",
    "CActorSiteOpPatch",
    "CActorSiteOpPersistentOffset",
    "CActorSiteOpOrbiter",
    "CActorSiteOpPhysicsImpact",
    "CActorSiteOpRandomPointInCircle",
    "CActorSiteOpRandomPointInCrossbar",
    "CActorSiteOpRandomPointInSphere",
    "CActorSiteOpRotationExplicit",
    "CActorSiteOpRotationRandom",
    "CActorSiteOpRotationVariancer",
    "CActorSiteOpRotator",
    "CActorSiteOpRotationSmooth",
    "CActorSiteOpSelectionOffset",
    "CActorSiteOpSerpentHead",
    "CActorSiteOpSerpentSegment",
    "CActorSiteOpShadow",
    "CActorSiteOpTether",
    "CActorSiteOpTipability",
    "CActorSiteOpTilter",
    "CActorSiteOpUp",
    "CActorSiteOpZ",
    "CActorSiteOpCursor",
    "CActorSiteOpYawLimiter",
    "CActorSiteOpPitchLimiter",
    "CActorSnapshot",
    "CActorStateMonitor",
    "CActorSquib",
    "CActorBatch",
    "CActorTerrain",
    "CActorTerrainDeformer",
    "CActorText",
    "CActorTurret",
    "CActorUnit",
    "CActorUnitRing",
    "CActorMissile",
    "CActorMinimap"
  ],
  EUnitStatusGroup: [
    "Owner",
    "Allied",
    "Enemy",
    "All"
  ],
  EClassIdCActorSupport: [],
  EUnitStatus: [
    "Shields",
    "Life",
    "Energy",
    "Cargo",
    "Progress",
    "Duration",
    "Magazine",
    "Workers",
    "Custom",
    "Charges"
  ],
  EFlyerDisplay: [
    "None",
    "Selected",
    "All"
  ],
  EClassIdCAlert: [
    "CAlert"
  ],
  EClassIdCArmyCategory: [
    "CArmyCategory"
  ],
  EArmyCategoryState: [
    "Locked",
    "Unlocked"
  ],
  EClassIdCArmyUnit: [
    "CArmyUnit"
  ],
  EArmyUnitState: [
    "Locked",
    "Unlocked",
    "Purchased",
    "Disabled"
  ],
  EClassIdCArmyUpgrade: [
    "CArmyUpgrade"
  ],
  EArmyUpgradeState: [
    "Locked",
    "Unlocked",
    "Purchased",
    "Disabled"
  ],
  EClassIdCArtifact: [
    "CArtifact"
  ],
  EClassIdCArtifactSlot: [
    "CArtifactSlot"
  ],
  EClassIdCAttachMethod: [
    "CAttachMethod",
    "CAttachMethodArcTest",
    "CAttachMethodBestMatch",
    "CAttachMethodFilter",
    "CAttachMethodAttachType",
    "CAttachMethodIncoming",
    "CAttachMethodLeastDeflection",
    "CAttachMethodNodeOccupancy",
    "CAttachMethodNodeOccupancy2",
    "CAttachMethodNumericField",
    "CAttachMethodPattern",
    "CAttachMethodPortAllocator",
    "CAttachMethodProximity",
    "CAttachMethodRandom",
    "CAttachMethodReduction",
    "CAttachMethodVolumesRequery",
    "CAttachMethodVolumesTargets",
    "CAttachMethodVolumesWeightedPick"
  ],
  EClassIdCBankCondition: [
    "CBankCondition",
    "CBankConditionCompare",
    "CBankConditionCompareValueCount",
    "CBankConditionCompareValueInteger",
    "CBankConditionCompareValueString",
    "CBankConditionCompareValueSum",
    "CBankConditionCombine",
    "CBankConditionCurrentMap"
  ],
  EClassIdCBeam: [
    "CBeam",
    "CBeamSync",
    "CBeamSyncSweeper",
    "CBeamAsync",
    "CBeamAsyncLinear",
    "CBeamAsyncShadow"
  ],
  EClassIdCBehavior: [
    "CBehavior",
    "CBehaviorAttackModifier",
    "CBehaviorAttribute",
    "CBehaviorUnitTracker",
    "CBehaviorBuff",
    "CBehaviorClickResponse",
    "CBehaviorConjoined",
    "CBehaviorCreepSource",
    "CBehaviorJump",
    "CBehaviorPowerSource",
    "CBehaviorPowerUser",
    "CBehaviorResource",
    "CBehaviorReveal",
    "CBehaviorSpawn",
    "CBehaviorVeterancy",
    "CBehaviorWander"
  ],
  EBehaviorCategory: [
    "Permanent",
    "Restorable",
    "Temporary",
    "Cloak",
    "Invulnerable",
    "Slow",
    "Fast",
    "Stun",
    "Reveal",
    "Magic",
    "Physical",
    "Aura",
    "Passive",
    "PassiveMagic",
    "TeleportRemove",
    "CanSteal",
    "TimedLife",
    "User1",
    "User2",
    "User3",
    "User4",
    "User5",
    "User6",
    "User7",
    "User8",
    "User9",
    "User10",
    "User11",
    "User12",
    "User13",
    "User14",
    "User15"
  ],
  EAttackModifierStage: [
    "Init",
    "Idle",
    "Waiting",
    "Applied",
    "Fired"
  ],
  EDamageLocation: [
    "Attacker",
    "Defender"
  ],
  EClassIdCBoost: [
    "CBoost"
  ],
  EClassIdCBundle: [
    "CBundle"
  ],
  EClassIdCButton: [
    "CButton"
  ],
  EClassIdCCamera: [
    "CCamera"
  ],
  EClassIdCCampaign: [
    "CCampaign"
  ],
  EClassIdCCharacter: [
    "CCharacter"
  ],
  EClassIdCCliff: [
    "CCliff"
  ],
  EClassIdCCliffMesh: [
    "CCliffMesh"
  ],
  EClassIdCColorStyle: [
    "CColorStyle"
  ],
  EUIColorMode: [],
  EUIColorRelation: [],
  EClassIdCCommander: [
    "CCommander"
  ],
  ECommanderTalentType: [
    "Passive",
    "Ability",
    "Bundle",
    "Unit"
  ],
  ECommanderMasteryTalentType: [
    "None",
    "Seconds",
    "Percent"
  ],
  EClassIdCConfig: [
    "CConfig"
  ],
  EPortraitOverlayType: [
    "Level",
    "HeroLeague",
    "TeamLeague"
  ],
  EClassIdCConsoleSkin: [
    "CConsoleSkin"
  ],
  EClassIdCConversation: [
    "CConversation"
  ],
  EClassIdCConversationState: [
    "CConversationState"
  ],
  EClassIdCCursor: [
    "CCursor"
  ],
  EClassIdCDataCollection: [
    "CDataCollection",
    "CDataCollectionUnit",
    "CDataCollectionUpgrade",
    "CDataCollectionAbil"
  ],
  EClassIdCDataCollectionPattern: [
    "CDataCollectionPattern"
  ],
  EClassIdCDecalPack: [
    "CDecalPack"
  ],
  EClassIdCDSP: [
    "CDSP",
    "CDSPChorus",
    "CDSPCompressor",
    "CDSPCustomCompressor",
    "CDSPDistortion",
    "CDSPEcho",
    "CDSPFlange",
    "CDSPHighPass",
    "CDSPLimiter",
    "CDSPLowPass",
    "CDSPLowPassSimple",
    "CDSPNormalize",
    "CDSPOscillator",
    "CDSPParamEQ",
    "CDSPPitchShift",
    "CDSPReverb"
  ],
  EClassIdCEffect: [
    "CEffect",
    "CEffectResponse",
    "CEffectAddTrackedUnit",
    "CEffectClearTrackedUnits",
    "CEffectAddTrackedUnits",
    "CEffectRemoveTrackedUnit",
    "CEffectApplyBehavior",
    "CEffectApplyForce",
    "CEffectApplyKinetic",
    "CEffectCancelOrder",
    "CEffectCreateHealer",
    "CEffectCreep",
    "CEffectCreatePersistent",
    "CEffectRandomPointInCircle",
    "CEffectCreateUnit",
    "CEffectDamage",
    "CEffectDestroyHealer",
    "CEffectDestroyPersistent",
    "CEffectEnumArea",
    "CEffectEnumTrackedUnits",
    "CEffectEnumMagazine",
    "CEffectEnumTransport",
    "CEffectEnumInventory",
    "CEffectLastTarget",
    "CEffectLoadContainer",
    "CEffectIssueOrder",
    "CEffectLaunchMissile",
    "CEffectModifyPlayer",
    "CEffectModifyUnit",
    "CEffectMorph",
    "CEffectRedirectMissile",
    "CEffectReleaseMagazine",
    "CEffectRemoveBehavior",
    "CEffectRemoveKinetic",
    "CEffectReturnMagazine",
    "CEffectSet",
    "CEffectSwitch",
    "CEffectTeleport",
    "CEffectTransferBehavior",
    "CEffectUseCalldown",
    "CEffectUseMagazine",
    "CEffectUserData"
  ],
  EClassIdCEmoticon: [
    "CEmoticon"
  ],
  EClassIdCEmoticonPack: [
    "CEmoticonPack"
  ],
  EClassIdCError: [],
  EClassIdCFootprint: [
    "CFootprint"
  ],
  EClassIdCFoW: [
    "CFoW"
  ],
  EClassIdCGame: [
    "CGame"
  ],
  EAllianceId: [
    "Passive",
    "Vision",
    "Control",
    "Spend",
    "Trade",
    "SeekHelp",
    "GiveHelp",
    "Chat",
    "Defeat",
    "Pushable",
    "Power"
  ],
  EAlliancePlayer: [
    "Control",
    "Upkeep"
  ],
  EFlagOperation: [
    "Set",
    "Clear",
    "Toggle"
  ],
  EPlayerType: [
    "None",
    "User",
    "Computer",
    "Neutral",
    "Hostile"
  ],
  ETargetFilter: [
    "Self",
    "Player",
    "Ally",
    "Neutral",
    "Enemy",
    "Air",
    "Ground",
    "Light",
    "Armored",
    "Biological",
    "Robotic",
    "Mechanical",
    "Psionic",
    "Massive",
    "Structure",
    "Hover",
    "Heroic",
    "User1",
    "Worker",
    "RawResource",
    "HarvestableResource",
    "Missile",
    "Destructible",
    "Item",
    "Uncommandable",
    "CanHaveEnergy",
    "CanHaveShields",
    "PreventDefeat",
    "PreventReveal",
    "Buried",
    "Cloaked",
    "Visible",
    "Stasis",
    "UnderConstruction",
    "Dead",
    "Revivable",
    "Hidden",
    "Hallucination",
    "Invulnerable",
    "HasEnergy",
    "HasShields",
    "Benign",
    "Passive",
    "Detector",
    "Radar",
    "Stunned",
    "Summoned",
    "Unstoppable",
    "Outer",
    "Resistant",
    "Silenced",
    "Dazed",
    "MapBoss",
    "Decaying",
    "Raisable",
    "HeroUnit",
    "NonBuildingUnit",
    "GroundUnit",
    "AirUnit",
    "Powerup",
    "PowerupOrItem",
    "NeutralHostile"
  ],
  EMarkerMatch: [
    "Id",
    "Link",
    "CasterPlayer",
    "CasterUnit"
  ],
  EHeightMap: [
    "Air",
    "Glide",
    "Ground"
  ],
  EPlane: [
    "Ground",
    "Air"
  ],
  EPlacementTest: [
    "Creep",
    "Power",
    "Fog",
    "IgnoreBlockers",
    "IgnoreInvisible",
    "Zone",
    "Cliff",
    "Density",
    "OriginSideOfFootprints"
  ],
  EUnitUserFlag: [
    "Unit",
    "ArmyUnit",
    "Hero",
    "Building",
    "Ancient",
    "Ward",
    "Item",
    "Powerup",
    "Projectile",
    "Destructible",
    "Tree",
    "Bridge",
    "CanSleep",
    "User14",
    "User15",
    "User16"
  ],
  EUnitVital: [
    "Life",
    "Shields",
    "Energy"
  ],
  EDamageType: [
    "Normal",
    "Enhanced",
    "Fire",
    "Cold",
    "Lightning",
    "Poison",
    "Disease",
    "Divine",
    "Magic",
    "Sonic",
    "Acid",
    "Force",
    "Death",
    "Mind",
    "Plant",
    "Defensive",
    "Demolition",
    "SlowPoison",
    "SpiritLink",
    "ShadowStrike",
    "Universal"
  ],
  EDamageCategory: [
    "Universal",
    "Magical",
    "Physical"
  ],
  EAttackType: [
    "Spell",
    "Normal",
    "Pierce",
    "Siege",
    "Magic",
    "Chaos",
    "Hero"
  ],
  EArmorType: [
    "Small",
    "Medium",
    "Large",
    "Fort",
    "Normal",
    "Hero",
    "Divine",
    "None"
  ],
  EDamageKind: [
    "Spell",
    "Melee",
    "Ranged",
    "Splash",
    "NoProc"
  ],
  EDeathType: [
    "Normal",
    "Remove",
    "Blast",
    "Disintegrate",
    "Eat",
    "Electrocute",
    "Eviscerate",
    "Fire",
    "Freeze",
    "Impact",
    "Morph",
    "Reincarnation",
    "Silentkill",
    "Squish",
    "Timeout",
    "Unlink",
    "UnderConstruction",
    "Salvage",
    "Cancel",
    "TrainingComplete",
    "TrainingCancel"
  ],
  ECooldownOperation: [
    "Default",
    "Add",
    "Multiply",
    "Min",
    "Max",
    "Set"
  ],
  EResourceType: [
    "Minerals",
    "Vespene",
    "Terrazine",
    "Custom"
  ],
  EEffectLocation: [
    "CasterUnit",
    "CasterPoint",
    "CasterUnitOrPoint",
    "CasterOuterUnit",
    "CasterOuterPoint",
    "CasterOuterUnitOrPoint",
    "SourceUnit",
    "SourcePoint",
    "SourceUnitOrPoint",
    "OuterUnit",
    "OuterPoint",
    "OuterUnitOrPoint",
    "TargetUnit",
    "TargetPoint",
    "TargetUnitOrPoint",
    "TargetOuterUnit",
    "TargetOuterPoint",
    "TargetOuterUnitOrPoint",
    "OriginUnit",
    "OriginPoint",
    "OriginUnitOrPoint"
  ],
  EEffectPlayer: [
    "Origin",
    "Creator",
    "Caster",
    "CasterOuter",
    "Outer",
    "Source",
    "Target",
    "TargetOuter",
    "Neutral",
    "Hostile"
  ],
  EEffectUnit: [
    "Caster",
    "CasterOuter",
    "Outer",
    "Source",
    "Target",
    "TargetOuter",
    "Origin"
  ],
  ETeamColor: [
    "Diffuse",
    "Emissive",
    "Selected",
    "Attacked"
  ],
  ETechCategory: [],
  EValueCompare: [
    "Eq",
    "NE",
    "LT",
    "GT",
    "LE",
    "GE"
  ],
  EBeacon: [
    "Army",
    "Defend",
    "Attack",
    "Harass",
    "Idle",
    "Auto",
    "Detect",
    "Scout",
    "Claim",
    "Expand",
    "Rally",
    "Custom1",
    "Custom2",
    "Custom3",
    "Custom4"
  ],
  ECustomBuildOpening: [
    "Invalid",
    "One",
    "Two",
    "Three",
    "Four",
    "Five"
  ],
  ECustomBuildLateGame: [
    "Invalid",
    "One",
    "Two",
    "Three",
    "Four",
    "Five"
  ],
  EUnitTaunt: [
    "Cheer",
    "Dance",
    "Tease"
  ],
  EEffectAmount: [
    "Absorbed",
    "Damaged",
    "Dodged",
    "Found",
    "Healed",
    "Killed",
    "Splashed",
    "LifeChanged",
    "ShieldsChanged",
    "EnergyChanged",
    "LifeLeeched",
    "ShieldsLeeched",
    "EnergyLeeched",
    "LifeGained",
    "ShieldsGained",
    "EnergyGained",
    "DamageInherited"
  ],
  EEffectHistory: [
    "Damage",
    "Death",
    "Healing",
    "Modifier"
  ],
  EGameCatalog: [
    "Abil",
    "Achievement",
    "AchievementTerm",
    "Actor",
    "ActorSupport",
    "Alert",
    "ArmyCategory",
    "ArmyUnit",
    "ArmyUpgrade",
    "Artifact",
    "ArtifactSlot",
    "AttachMethod",
    "BankCondition",
    "Beam",
    "Behavior",
    "Bundle",
    "Boost",
    "Button",
    "Camera",
    "Campaign",
    "Character",
    "Cliff",
    "CliffMesh",
    "ColorStyle",
    "Commander",
    "Config",
    "ConsoleSkin",
    "Conversation",
    "ConversationState",
    "Cursor",
    "DecalPack",
    "DSP",
    "Effect",
    "Emoticon",
    "EmoticonPack",
    "Error",
    "Footprint",
    "FoW",
    "Game",
    "GameUI",
    "Herd",
    "HerdNode",
    "Hero",
    "HeroAbil",
    "HeroStat",
    "Item",
    "ItemClass",
    "ItemContainer",
    "Kinetic",
    "LensFlareSet",
    "Light",
    "Location",
    "Loot",
    "Map",
    "Model",
    "Mount",
    "Mover",
    "Objective",
    "PhysicsMaterial",
    "Ping",
    "PortraitPack",
    "Preload",
    "PremiumMap",
    "Race",
    "RaceBannerPack",
    "Requirement",
    "RequirementNode",
    "Reverb",
    "Reward",
    "ScoreResult",
    "ScoreValue",
    "Shape",
    "Skin",
    "SkinPack",
    "Sound",
    "SoundExclusivity",
    "SoundMixSnapshot",
    "Soundtrack",
    "Spray",
    "SprayPack",
    "TacCooldown",
    "Tactical",
    "Talent",
    "TalentProfile",
    "TargetFind",
    "TargetSort",
    "Terrain",
    "TerrainObject",
    "TerrainTex",
    "Texture",
    "TextureSheet",
    "Tile",
    "Trophy",
    "Turret",
    "Unit",
    "Upgrade",
    "User",
    "Validator",
    "VoiceOver",
    "VoicePack",
    "WarChest",
    "WarChestSeason",
    "Water",
    "Weapon",
    "StimPack",
    "Accumulator",
    "PlayerResponse",
    "DataCollection",
    "DataCollectionPattern"
  ],
  EClassIdCGameUI: [
    "CGameUI"
  ],
  EUnitColorStyle: [
    "Normal",
    "OverrideMinimap",
    "OverrideWorld"
  ],
  EHotkey: [
    "FPS",
    "Music",
    "Sound",
    "PTT",
    "DisplayMode",
    "ChatAll",
    "ChatAllies",
    "ChatCancel",
    "ChatDefault",
    "ChatIndividual",
    "ChatRecipient",
    "ChatSend",
    "DialogDismiss",
    "MenuAchievements",
    "MenuGame",
    "MenuMessages",
    "MenuHelp",
    "MenuSocial",
    "LeaderNone",
    "LeaderResources",
    "LeaderIncome",
    "LeaderSpending",
    "LeaderUnits",
    "LeaderStructures",
    "LeaderUnitsLost",
    "LeaderProduction",
    "LeaderUpgrades",
    "LeaderArmy",
    "LeaderAPM",
    "LeaderCPM",
    "ObserveAllPlayers",
    "ObserveAutoCamera",
    "ObserveClearSelection",
    "ObserveCommentator",
    "ObservePlayer0",
    "ObservePlayer1",
    "ObservePlayer2",
    "ObservePlayer3",
    "ObservePlayer4",
    "ObservePlayer5",
    "ObservePlayer6",
    "ObservePlayer7",
    "ObservePlayer8",
    "ObservePlayer9",
    "ObservePlayer10",
    "ObservePlayer11",
    "ObservePlayer12",
    "ObservePlayer13",
    "ObservePlayer14",
    "ObservePlayer15",
    "ObservePreview",
    "ObserveSelected",
    "ObserveStatusBars",
    "ObserveZoomCameraLevel1",
    "ObserveZoomCameraLevel2",
    "NamePanel",
    "StatPanelResources",
    "StatPanelArmySupply",
    "StatPanelUnitsLost",
    "StatPanelAPM",
    "StatPanelCPM",
    "ToggleVersusModeSides",
    "ToggleWorldPanel",
    "ConversationSkipOne",
    "CinematicSkip",
    "AICommunication",
    "AIArmy",
    "AIScout",
    "AIDetect",
    "AIExpand",
    "AIBuild",
    "AIClearAll",
    "AIDelete",
    "AIExit",
    "AICancel",
    "AlertRecall",
    "ArmySelect",
    "CameraCenter",
    "CameraFollow",
    "CameraMoveUp",
    "CameraMoveDown",
    "CameraMoveLeft",
    "CameraMoveRight",
    "CameraTurnLeft",
    "CameraTurnRight",
    "CameraZoomFirst",
    "CameraZoomLast",
    "CameraZoomNext",
    "CameraZoomPrev",
    "CameraPush",
    "CommanderAbility0",
    "CommanderAbility1",
    "CommanderAbility2",
    "CommanderAbility3",
    "ControlGroupAppend0",
    "ControlGroupAppend1",
    "ControlGroupAppend2",
    "ControlGroupAppend3",
    "ControlGroupAppend4",
    "ControlGroupAppend5",
    "ControlGroupAppend6",
    "ControlGroupAppend7",
    "ControlGroupAppend8",
    "ControlGroupAppend9",
    "ControlGroupAppendAndSteal0",
    "ControlGroupAppendAndSteal1",
    "ControlGroupAppendAndSteal2",
    "ControlGroupAppendAndSteal3",
    "ControlGroupAppendAndSteal4",
    "ControlGroupAppendAndSteal5",
    "ControlGroupAppendAndSteal6",
    "ControlGroupAppendAndSteal7",
    "ControlGroupAppendAndSteal8",
    "ControlGroupAppendAndSteal9",
    "ControlGroupAssign0",
    "ControlGroupAssign1",
    "ControlGroupAssign2",
    "ControlGroupAssign3",
    "ControlGroupAssign4",
    "ControlGroupAssign5",
    "ControlGroupAssign6",
    "ControlGroupAssign7",
    "ControlGroupAssign8",
    "ControlGroupAssign9",
    "ControlGroupAssignAndSteal0",
    "ControlGroupAssignAndSteal1",
    "ControlGroupAssignAndSteal2",
    "ControlGroupAssignAndSteal3",
    "ControlGroupAssignAndSteal4",
    "ControlGroupAssignAndSteal5",
    "ControlGroupAssignAndSteal6",
    "ControlGroupAssignAndSteal7",
    "ControlGroupAssignAndSteal8",
    "ControlGroupAssignAndSteal9",
    "ControlGroupRecall0",
    "ControlGroupRecall1",
    "ControlGroupRecall2",
    "ControlGroupRecall3",
    "ControlGroupRecall4",
    "ControlGroupRecall5",
    "ControlGroupRecall6",
    "ControlGroupRecall7",
    "ControlGroupRecall8",
    "ControlGroupRecall9",
    "GameSpeedDec",
    "GameSpeedInc",
    "GameTooltipsOn",
    "HeroCharacterSheetPanel",
    "HeroLeaderPanel",
    "HeroSelect0",
    "HeroSelect1",
    "HeroSelect2",
    "HeroSelect3",
    "HeroSelect4",
    "HeroSelect5",
    "HeroSelect6",
    "HeroSelect7",
    "HeroTalentTreeSelection",
    "IdleWorker",
    "InventoryButtonAlt0",
    "InventoryButtonAlt1",
    "InventoryButtonAlt2",
    "InventoryButtonAlt3",
    "InventoryButtonAlt4",
    "InventoryButtonAlt5",
    "InventoryButtonAlt6",
    "InventoryButtonAlt7",
    "InventoryButtonUseSelf0",
    "InventoryButtonUseSelf1",
    "InventoryButtonUseSelf2",
    "InventoryButtonUseSelf3",
    "InventoryButtonUseSelf4",
    "InventoryButtonUseSelf5",
    "InventoryButtonUseSelf6",
    "InventoryButtonUseSelf7",
    "InventoryButtonUse0",
    "InventoryButtonUse1",
    "InventoryButtonUse2",
    "InventoryButtonUse3",
    "InventoryButtonUse4",
    "InventoryButtonUse5",
    "InventoryButtonUse6",
    "InventoryButtonUse7",
    "MinimapColors",
    "MinimapPing",
    "MinimapTargetingView",
    "MinimapNormalView",
    "MinimapTerrain",
    "PauseGame",
    "Ping",
    "PingSelection0",
    "PingSelection1",
    "PingSelection2",
    "PingSelection3",
    "PingSelection4",
    "PingSelection5",
    "QuickPing",
    "QuickSave",
    "QuickHeroTalentTreeSelection",
    "QuickHeroTalentTreeSelection0",
    "QuickHeroTalentTreeSelection1",
    "QuickHeroTalentTreeSelection2",
    "QuickHeroTalentTreeSelection3",
    "QuickHeroTalentTreeSelection4",
    "EmoteMenu",
    "ReplayPlayPause",
    "ReplayRestart",
    "ReplaySkipBack",
    "ReplaySkipNext",
    "ReplaySpeedDec",
    "ReplaySpeedInc",
    "ReplayStop",
    "ReplayHide",
    "Screenshot",
    "SelectionCancelDrag",
    "Selection",
    "SmartCommand",
    "Spotlight",
    "StatusAll",
    "StatusOwner",
    "StatusAlly",
    "StatusEnemy",
    "SubgroupNext",
    "SubgroupPrev",
    "TargetCancel",
    "TargetChoose",
    "TeamResources",
    "TownCamera",
    "VideoRecord",
    "WarpIn",
    "CommandButtonAlt00",
    "CommandButtonAlt01",
    "CommandButtonAlt02",
    "CommandButtonAlt03",
    "CommandButtonAlt04",
    "CommandButtonAlt05",
    "CommandButtonAlt06",
    "CommandButtonAlt07",
    "CommandButtonAlt08",
    "CommandButtonAlt09",
    "CommandButtonAlt10",
    "CommandButtonAlt11",
    "CommandButtonAlt12",
    "CommandButtonAlt13",
    "CommandButtonAlt14",
    "CommandButtonSelf00",
    "CommandButtonSelf01",
    "CommandButtonSelf02",
    "CommandButtonSelf03",
    "CommandButtonSelf04",
    "CommandButtonSelf05",
    "CommandButtonSelf06",
    "CommandButtonSelf07",
    "CommandButtonSelf08",
    "CommandButtonSelf09",
    "CommandButtonSelf10",
    "CommandButtonSelf11",
    "CommandButtonSelf12",
    "CommandButtonSelf13",
    "CommandButtonSelf14",
    "CommandButton00",
    "CommandButton01",
    "CommandButton02",
    "CommandButton03",
    "CommandButton04",
    "CommandButton05",
    "CommandButton06",
    "CommandButton07",
    "CommandButton08",
    "CommandButton09",
    "CommandButton10",
    "CommandButton11",
    "CommandButton12",
    "CommandButton13",
    "CommandButton14",
    "CameraSave0",
    "CameraSave1",
    "CameraSave2",
    "CameraSave3",
    "CameraSave4",
    "CameraSave5",
    "CameraSave6",
    "CameraSave7",
    "CameraView0",
    "CameraView1",
    "CameraView2",
    "CameraView3",
    "CameraView4",
    "CameraView5",
    "CameraView6",
    "CameraView7",
    "UIEditorToggle",
    "UIEditorReload",
    "UIEditorSaveSelected",
    "UIEditorSaveAll",
    "UIEditorUndo",
    "UIEditorRedo",
    "UIEditorDeselect",
    "UIEditorShowInfoTooltip",
    "UIEditorToggleVisible",
    "UIEditorHoverControls",
    "UIEditorLockInfoTooltip",
    "UIEditorOutlineAnchors",
    "UIEditorIncreaseGridSpacing",
    "UIEditorDecreaseGridSpacing",
    "UIEditorToggleStateGroupOverlay",
    "UIEditorBreakToDebugger",
    "UIEditorSize720x406",
    "UIEditorSize800x600",
    "UIEditorSize1024x768",
    "UIEditorSize1280x1024",
    "UIEditorSize1280x960",
    "UIEditorSize1280x720",
    "UIEditorSize1680x1050",
    "UIEditorSize1400x1050",
    "UIEditorSize1920x1200",
    "UIEditorSize1920x1080",
    "UIEditorSize1600x1200",
    "UIEditorSize2048x1536",
    "UIEditorSize2560x1600",
    "UIEditorSize2560x2048",
    "UIEditorSize4096x2560",
    "UIEditorSize4096x2304",
    "UIEditorSize4096x3072"
  ],
  EPathLocation: [
    "World",
    "Minimap"
  ],
  ENydusLink: [
    "BreakingNews",
    "PTRAvailable",
    "AccountManagement",
    "AccountPurchase",
    "AccountTrialUpgrade",
    "AccountNew",
    "AccountTrial",
    "SecurityPassword",
    "Forum",
    "Community",
    "FeedHomepage",
    "FeedHomepageBackground",
    "FeedCommunity",
    "FeedFeaturedMaps",
    "FeedLiveEvent",
    "Store",
    "SecurityHelp",
    "Support",
    "OnlineGuide",
    "Copyright",
    "ParentalControls",
    "Regions",
    "CacheList",
    "RefundPolicy",
    "TermsOfService",
    "TermsOfSale",
    "RecruitFriend",
    "LowVirtualMemory",
    "StarterEdition",
    "PremiumMap",
    "StimpackInfo",
    "MaintenanceInfo",
    "ExternalLink",
    "CCPA"
  ],
  EClassIdCHerd: [
    "CHerd"
  ],
  EClassIdCHerdNode: [
    "CHerdNode"
  ],
  EClassIdCHero: [
    "CHero"
  ],
  EHeroState: [
    "Locked",
    "Unlocked"
  ],
  EHeroAbilCategoryState: [
    "Locked",
    "Unlocked"
  ],
  EHeroCutsceneSize: [
    "Small",
    "Medium",
    "Large"
  ],
  EHeroFlag: [
    "Flyer",
    "Random",
    "UsesMount",
    "ExcludeFromMapIntro",
    "GoodForModeA",
    "GoodForModeB",
    "AllowAIRandomSelection",
    "ShowInStore"
  ],
  EHeroRole: [
    "Warrior",
    "Damage",
    "Support",
    "Specialist"
  ],
  EHeroDifficulty: [
    "Easy",
    "Medium",
    "Hard",
    "VeryHard"
  ],
  EHeroVO: [
    "AIAttack",
    "AICaution",
    "AIGoodJob",
    "AIHeal",
    "AIMercCapture",
    "AIOnMyWay",
    "AIRetreat",
    "AIUhOh",
    "Celebrate",
    "Cheer",
    "Comeback",
    "EndEnemyKillSpree",
    "GetHit",
    "GetHitLarge",
    "GetHitSmall",
    "GlueExamineLocked",
    "GlueExaminePurchased",
    "GlueGift",
    "GluePurchase",
    "GlueTrial",
    "GlueWaitLocked",
    "GlueWaitPurchased",
    "Goodbye",
    "Healed",
    "Hello",
    "IntroAgree",
    "IntroBoast",
    "IntroQuestion",
    "IntroResponse",
    "KillGeneric",
    "Laugh",
    "No",
    "PingAssistHero",
    "PingAssistMe",
    "PingAttackCore",
    "PingAttackHere",
    "PingAttackHero",
    "PingAttackMercCamp",
    "PingAttackTown",
    "PingAttackWatchTower",
    "PingDefendCore",
    "PingDefendHere",
    "PingDefendTown",
    "PingDefendWatchTower",
    "Pissed",
    "Resurrected",
    "Revive",
    "Sorry",
    "SpecChosen",
    "TeamKilled",
    "Thanks",
    "UILockin",
    "WellPlayed",
    "WorthIt"
  ],
  EHeroGender: [
    "Male",
    "Female"
  ],
  EHeroUniverse: [
    "StarCraft",
    "Warcraft",
    "Diablo",
    "Heroes",
    "Retro"
  ],
  EHeroAbilFlag: [
    "ShowInHeroSelect",
    "UsesCharges",
    "AffectedByCooldownReduction",
    "AffectedByOverdrive",
    "Heroic",
    "Trait",
    "MountReplacement",
    "HideHotkey"
  ],
  EHeroImageFacing: [
    "Left",
    "Right",
    "Mid"
  ],
  EHeroAITalentBuildType: [
    "General",
    "Damage",
    "Tank",
    "Support"
  ],
  EClassIdCHeroAbil: [
    "CHeroAbil"
  ],
  EHeroAbilState: [
    "Locked",
    "Unlocked",
    "New"
  ],
  EClassIdCHeroStat: [
    "CHeroStat"
  ],
  EHeroStatState: [
    "Downgrade",
    "Unchanged",
    "Upgrade"
  ],
  EClassIdCItem: [
    "CItem",
    "CItemAbil",
    "CItemAbilPowerUp",
    "CItemEffect",
    "CItemEffectInstant",
    "CItemEffectTarget"
  ],
  EClassIdCItemClass: [
    "CItemClass"
  ],
  EClassIdCItemContainer: [
    "CItemContainer"
  ],
  EClassIdCKinetic: [
    "CKinetic",
    "CKineticFollow",
    "CKineticRotate",
    "CKineticSequence",
    "CKineticSet",
    "CKineticTranslate",
    "CKineticDistance"
  ],
  EClassIdCLensFlareSet: [
    "CLensFlareSet"
  ],
  EClassIdCLight: [
    "CLight"
  ],
  EGameTimeEvent: [
    "Dawn",
    "Dusk"
  ],
  ETimeOfDayValue: [
    "Value",
    "Hours",
    "Minutes",
    "Seconds"
  ],
  EClassIdCLocation: [
    "CLocation"
  ],
  EMissionState: [
    "Locked",
    "Unlocked",
    "Hidden",
    "Complete"
  ],
  EClassIdCLoot: [
    "CLoot",
    "CLootSpawn",
    "CLootEffect",
    "CLootItem",
    "CLootSet",
    "CLootUnit"
  ],
  EClassIdCMap: [
    "CMap"
  ],
  EMapKind: [
    "Mission",
    "Story",
    "Upgrade"
  ],
  EClassIdCModel: [
    "CModel",
    "CModelFoliage"
  ],
  EAnimProp: [
    "00",
    "01",
    "02",
    "03",
    "04",
    "05",
    "06",
    "07",
    "08",
    "09",
    "10",
    "11",
    "12",
    "13",
    "14",
    "15",
    "16",
    "17",
    "18",
    "19",
    "20",
    "21",
    "22",
    "23",
    "24",
    "25",
    "26",
    "27",
    "28",
    "29",
    "30",
    "31",
    "32",
    "33",
    "34",
    "35",
    "36",
    "37",
    "38",
    "39",
    "40",
    "41",
    "42",
    "43",
    "44",
    "45",
    "46",
    "47",
    "48",
    "49",
    "50",
    "51",
    "52",
    "53",
    "54",
    "55",
    "56",
    "57",
    "58",
    "59",
    "60",
    "61",
    "62",
    "63",
    "64",
    "65",
    "66",
    "67",
    "68",
    "69",
    "70",
    "71",
    "72",
    "73",
    "74",
    "75",
    "76",
    "77",
    "78",
    "79",
    "80",
    "81",
    "82",
    "83",
    "84",
    "85",
    "86",
    "87",
    "88",
    "89",
    "90",
    "91",
    "92",
    "93",
    "94",
    "95",
    "96",
    "97",
    "98",
    "99",
    "VariationEnd",
    "IGNORE",
    "Default",
    "Stand",
    "A",
    "B",
    "C",
    "D",
    "E",
    "F",
    "G",
    "H",
    "I",
    "J",
    "K",
    "L",
    "M",
    "N",
    "O",
    "P",
    "Q",
    "R",
    "S",
    "T",
    "U",
    "V",
    "W",
    "X",
    "Y",
    "Z",
    "Zero",
    "One",
    "Two",
    "Three",
    "Four",
    "Five",
    "Six",
    "Seven",
    "Eight",
    "Nine",
    "Alternate",
    "Attached",
    "Attack",
    "Back",
    "Birth",
    "Blast",
    "Blink",
    "Block",
    "Build",
    "Burrow",
    "Channel",
    "Cinematic",
    "Cloak",
    "Close",
    "Click",
    "Complex",
    "Corrupted",
    "Cover",
    "Creep",
    "Custom",
    "Dance",
    "Dead",
    "Death",
    "Defeat",
    "Detect",
    "Dialogue",
    "Disintegrate",
    "Dominant",
    "Double",
    "Down",
    "Eat",
    "Electrocute",
    "End",
    "Enemy",
    "Equal",
    "Eviscerate",
    "Far",
    "Fast",
    "Fidget",
    "Fire",
    "Flail",
    "Fling",
    "Fly",
    "Forward",
    "Freeze",
    "Gather",
    "GLbirth",
    "GLdeath",
    "GLdead",
    "GLstand",
    "Glow",
    "Hearth",
    "Highlight",
    "Hover",
    "Hold",
    "In",
    "Inferior",
    "Interact",
    "Intro",
    "Jump",
    "Kill",
    "Land",
    "Large",
    "Left",
    "Level",
    "Listen",
    "Lighting",
    "Load",
    "Medium",
    "Melee",
    "Morph",
    "Mount",
    "NearImpact",
    "Omni",
    "Out",
    "Penetrate",
    "Pickup",
    "Placement",
    "Portrait",
    "Pose",
    "Range",
    "Ready",
    "Reload",
    "Restart",
    "Resurrect",
    "Ride",
    "Right",
    "Run",
    "Scared",
    "Shield",
    "Silentkill",
    "Simple",
    "Slow",
    "Small",
    "Spell",
    "Squish",
    "Standup",
    "Start",
    "Stun",
    "Superior",
    "Surf",
    "Talk",
    "Taunt",
    "Teleport",
    "Thrown",
    "Turbo",
    "Turn",
    "Unburrow",
    "Unload",
    "Unpowered",
    "Up",
    "Victory",
    "Walk",
    "Work",
    "Wounded",
    "Angry",
    "Happy",
    "Sad",
    "AngryEyes",
    "ClosedEyes",
    "FearEyes",
    "HappyEyes",
    "NeutralEyes",
    "SadEyes",
    "SeriousEyes",
    "SurpriseEyes",
    "Arm",
    "Chest",
    "Eye",
    "Leg",
    "Adjutant",
    "Dehaka",
    "Evomaster",
    "Horner",
    "Kerrigan",
    "Lasarra",
    "Raynor",
    "Stukov",
    "Valerian",
    "Zagara",
    "Protoss",
    "Terran",
    "Zerg",
    "Alternateex",
    "Berserk",
    "Bone",
    "Chain",
    "Combat",
    "Complete",
    "Critical",
    "Decay",
    "Defend",
    "Devour",
    "Dissipate",
    "Drain",
    "EatTree",
    "Entangle",
    "Fill",
    "Flesh",
    "Gold",
    "Hit",
    "Light",
    "Lightning",
    "Looping",
    "Lumber",
    "Moderate",
    "Monkey",
    "Off",
    "Puke",
    "Severe",
    "Slam",
    "Sleep",
    "Spiked",
    "Spin",
    "StageFirst",
    "StageSecond",
    "StageThird",
    "StageFourth",
    "StageFifth",
    "Swim",
    "Throw",
    "Upgrade",
    "Ridebeast",
    "Ridebike",
    "Ridenone",
    "Ridesurf"
  ],
  EClassIdCMount: [
    "CMount"
  ],
  EMountFlag: [
    "FreePlay",
    "IsVariation"
  ],
  EMountVO: [
    "Mounted",
    "Dismounted",
    "Looping",
    "Moving",
    "Stationary"
  ],
  EClassIdCMover: [
    "CMover",
    "CMoverAvoid",
    "CMoverFlock",
    "CMoverMissile",
    "CMoverNull"
  ],
  EClassIdCObjective: [
    "CObjective"
  ],
  EObjectiveType: [
    "Optional",
    "Primary"
  ],
  EObjectiveReward: [
    "DNA",
    "Infestation",
    "Mutagen"
  ],
  EClassIdCPhysicsMaterial: [
    "CPhysicsMaterial"
  ],
  EClassIdCPing: [
    "CPing"
  ],
  EPingFlag: [
    "UseUnitTeamColor",
    "UseUnitVisibility"
  ],
  EClassIdCPlayerResponse: [
    "CPlayerResponse",
    "CPlayerResponseUnit",
    "CPlayerResponseUnitDamage",
    "CPlayerResponseUnitDeath",
    "CPlayerResponseUnitBirth"
  ],
  EClassIdCPortraitPack: [
    "CPortraitPack"
  ],
  EClassIdCPreload: [
    "CPreload",
    "CPreloadAsset",
    "CPreloadScene",
    "CPreloadActor",
    "CPreloadConversation",
    "CPreloadModel",
    "CPreloadSound",
    "CPreloadUnit"
  ],
  EClassIdCPremiumMap: [
    "CPremiumMap"
  ],
  EClassIdCRace: [
    "CRace"
  ],
  EClassIdCRaceBannerPack: [
    "CRaceBannerPack"
  ],
  EClassIdCRequirement: [
    "CRequirement"
  ],
  EClassIdCRequirementNode: [
    "CRequirementNode"
  ],
  EClassIdCReverb: [
    "CReverb"
  ],
  EClassIdCReward: [
    "CReward",
    "CRewardDecal",
    "CRewardIcon",
    "CRewardModel",
    "CRewardPortrait",
    "CRewardBadge",
    "CRewardPoints",
    "CRewardTrophy",
    "CRewardEmoticon",
    "CRewardVoicePack",
    "CRewardPortraitInGame",
    "CRewardConsoleSkin",
    "CRewardSpray",
    "CRewardSprayUseDecal",
    "CRewardRaceBanner",
    "CRewardStim"
  ],
  EClassIdCScoreResult: [
    "CScoreResult",
    "CScoreResultRoot",
    "CScoreResultScore",
    "CScoreResultGraph",
    "CScoreResultPane",
    "CScoreResultBuildOrder",
    "CScoreResultCallouts",
    "CScoreResultExperience",
    "CScoreResultPerformance"
  ],
  EClassIdCScoreValue: [
    "CScoreValue",
    "CScoreValueCustom",
    "CScoreValueStandard",
    "CScoreValueConstant",
    "CScoreValueCombine"
  ],
  EClassIdCShape: [
    "CShape",
    "CShapeArc",
    "CShapeQuad"
  ],
  EClassIdCSkin: [
    "CSkin"
  ],
  EClassIdCSkinPack: [
    "CSkinPack"
  ],
  EClassIdCSound: [
    "CSound"
  ],
  ESoundCategory: [
    "Test",
    "ME",
    "Movie",
    "TV",
    "Dialogue",
    "Mission",
    "Music",
    "Other",
    "Ambient",
    "SAmbient",
    "Alert",
    "Death",
    "Ready",
    "Spell",
    "SpellOneshotImpact",
    "SpellOneshotLaunch",
    "Combat",
    "Voice",
    "Message",
    "UI",
    "UIMovie",
    "Flames",
    "Build",
    "Gather",
    "Doodad",
    "SEmitters",
    "SPieces",
    "Foley",
    "Movement",
    "User1",
    "User2",
    "User3",
    "User4",
    "User5",
    "User6",
    "User7",
    "User8",
    "User9",
    "User10",
    "User11",
    "User12",
    "User13",
    "User14",
    "User15",
    "User16",
    "User17",
    "User18",
    "User19",
    "User20",
    "User21",
    "User22",
    "User23",
    "User24",
    "User25",
    "User26",
    "User27",
    "User28",
    "User29",
    "User30",
    "User31",
    "User32",
    "User33",
    "User34",
    "User35"
  ],
  EClassIdCSoundExclusivity: [
    "CSoundExclusivity"
  ],
  EClassIdCSoundMixSnapshot: [
    "CSoundMixSnapshot"
  ],
  EClassIdCSoundtrack: [
    "CSoundtrack"
  ],
  ESoundtrackCategory: [
    "Ambience",
    "Music"
  ],
  EClassIdCSpray: [
    "CSpray"
  ],
  EClassIdCSprayPack: [
    "CSprayPack"
  ],
  EClassIdCStimPack: [
    "CStimPack"
  ],
  EClassIdCTacCooldown: [
    "CTacCooldown"
  ],
  EClassIdCTactical: [
    "CTactical",
    "CTacticalOrder",
    "CTacticalSet"
  ],
  EClassIdCTalent: [
    "CTalent"
  ],
  ETalentModification: [
    "None",
    "CooldownReduction",
    "FlatModification",
    "MultiplyLevelModification",
    "StringReplacement",
    "CatalogReplacement"
  ],
  EClassIdCTalentProfile: [
    "CTalentProfile"
  ],
  ETalentProfileFlag: [
    "Hidden"
  ],
  EClassIdCTargetFind: [
    "CTargetFind",
    "CTargetFindBestPoint",
    "CTargetFindWorkerRallyPoint",
    "CTargetFindRallyPoint",
    "CTargetFindEnumArea",
    "CTargetFindEffect",
    "CTargetFindLastAttacker",
    "CTargetFindOffset",
    "CTargetFindOrder",
    "CTargetFindSet"
  ],
  EClassIdCTargetSort: [
    "CTargetSort",
    "CTargetSortAlliance",
    "CTargetSortAngle",
    "CTargetSortBehaviorCount",
    "CTargetSortBehaviorDuration",
    "CTargetSortChargeCount",
    "CTargetSortChargeRegen",
    "CTargetSortCooldown",
    "CTargetSortDistance",
    "CTargetSortField",
    "CTargetSortInterruptible",
    "CTargetSortMarker",
    "CTargetSortPowerSourceLevel",
    "CTargetSortPowerUserLevel",
    "CTargetSortPriority",
    "CTargetSortRandom",
    "CTargetSortValidator",
    "CTargetSortVeterancy",
    "CTargetSortVital",
    "CTargetSortVitalFraction"
  ],
  EClassIdCTerrain: [
    "CTerrain"
  ],
  EClassIdCTerrainObject: [
    "CTerrainObject"
  ],
  EClassIdCTerrainTex: [
    "CTerrainTex"
  ],
  EClassIdCTexture: [
    "CTexture"
  ],
  EClassIdCTextureSheet: [
    "CTextureSheet"
  ],
  EClassIdCTile: [
    "CTile"
  ],
  EClassIdCTrophy: [
    "CTrophy"
  ],
  EClassIdCTurret: [
    "CTurret"
  ],
  EClassIdCUnit: [
    "CUnit",
    "CUnitHero"
  ],
  EUnitFlag: [
    "Bounce",
    "Turnable",
    "Movable",
    "Worker",
    "CreateVisible",
    "Unclickable",
    "Uncommandable",
    "Unhighlightable",
    "Untooltipable",
    "Unselectable",
    "Untargetable",
    "Uncursorable",
    "Hero",
    "HiddenCargoUI",
    "IndividualSubgroups",
    "NoDraw",
    "PreventReveal",
    "PreventDefeat",
    "PreventDestroy",
    "PenaltyRevealed",
    "Uncloakable",
    "Missile",
    "Undetectable",
    "Unradarable",
    "UseLineOfSight",
    "KillCredit",
    "TownAlert",
    "Invulnerable",
    "Destructible",
    "Cloaked",
    "Buried",
    "NoScore",
    "IgnoreTerrainZInit",
    "TurnBeforeMove",
    "AlwaysThreatens",
    "NoDeathEvent",
    "NoPortraitTalk",
    "TownCamera",
    "AIThreatGround",
    "AIThreatAir",
    "AILifetime",
    "AISplash",
    "AIHighPrioTarget",
    "AISplitter",
    "AIDefense",
    "AICaster",
    "AISupport",
    "AICantAddToWave",
    "ShowResources",
    "ArmorDisabledWhileConstructing",
    "Pawnable",
    "AIFleeDamageDisabled",
    "AIPressForwardDisabled",
    "AIObservatory",
    "ForceCollisionCheck",
    "AIChangeling",
    "ShareControl",
    "BuiltOnOptional",
    "AcquireRally",
    "AIAllowSuicideOverride",
    "AIForceTactical",
    "VisionTestCenterOnly",
    "Unstoppable",
    "AIPreferBurrow",
    "ClearRallyOnDeath",
    "ClearRallyOnTargetLost",
    "SelectableWhileDead",
    "TargetableWhileDead",
    "IgnoreAttackAlert",
    "PreferLastAttackTarget",
    "ResumeLastMoveOrder",
    "AIResourceBlocker",
    "ArmySelect",
    "Resistant",
    "PlayerRevivable",
    "AIMakeIgnore",
    "AIPreplacedForceBully",
    "StatTrackAbilities",
    "StatTrackDamageDone",
    "StatTrackDamageReceived",
    "StatTrackCreation",
    "CameraFollow",
    "LeechBehaviorShieldDamage",
    "TownStructureWall",
    "TownStructureGate",
    "TownStructureTownHall",
    "TownStructureCannonTower",
    "TownStructureMoonwell",
    "TownStructureCore",
    "HideFromHarvestingCount",
    "TreatStructureAsUnitForSelection",
    "NonBuildingUnit",
    "NeverThink",
    "GrantLevelKillXP",
    "UseOuterRadius",
    "FootprintAlwaysIgnoreHeight",
    "FootprintPersistRotate"
  ],
  EUnitCollide: [
    "Land1",
    "Land2",
    "Land3",
    "Land4",
    "Land5",
    "Land6",
    "Land7",
    "Land8",
    "Land9",
    "Land10",
    "Land11",
    "Land12",
    "Land13",
    "Land14",
    "Land15",
    "Land16",
    "Air1",
    "Air2",
    "Air3",
    "Air4",
    "Air5",
    "Air6",
    "Air7",
    "Air8",
    "Air9",
    "Air10",
    "Air11",
    "Air12",
    "Air13",
    "Air14",
    "Air15",
    "Air16"
  ],
  EUnitAttribute: [
    "Light",
    "Armored",
    "Biological",
    "Mechanical",
    "Robotic",
    "Psionic",
    "Massive",
    "Structure",
    "Hover",
    "Heroic",
    "Summoned",
    "User1",
    "MapBoss"
  ],
  ECmdFlags: [],
  EClassIdCUpgrade: [
    "CUpgrade"
  ],
  EUpgradeOperation: [
    "Add",
    "Subtract",
    "AddBaseMultiply",
    "SubtractBaseMultiply",
    "Multiply",
    "Divide",
    "Set"
  ],
  EClassIdCUser: [
    "CUser"
  ],
  EUserType: [
    "AbilCmd",
    "Actor",
    "Color",
    "Compare",
    "Fixed",
    "GameLink",
    "Image",
    "Int",
    "Model",
    "Movie",
    "Sound",
    "String",
    "Text",
    "Unit",
    "Upgrade",
    "User"
  ],
  EClassIdCValidator: [
    "CValidator",
    "CValidatorCombine",
    "CValidatorCondition",
    "CValidatorFunction",
    "CValidatorEffect",
    "CValidatorEffectCompare",
    "CValidatorEffectCompareDodged",
    "CValidatorEffectCompareEvaded",
    "CValidatorEffectTreeUserData",
    "CValidatorGameCompareTimeEvent",
    "CValidatorGameCompareTimeOfDay",
    "CValidatorGameCompareTerrain",
    "CValidatorGameCommanderActive",
    "CValidatorLocation",
    "CValidatorLocationCompareCliffLevel",
    "CValidatorLocationComparePower",
    "CValidatorLocationCompareRange",
    "CValidatorLocationArc",
    "CValidatorLocationCreep",
    "CValidatorLocationCrossChasm",
    "CValidatorLocationCrossCliff",
    "CValidatorLocationEnumArea",
    "CValidatorLocationPathable",
    "CValidatorLocationInPlayableMapArea",
    "CValidatorLocationPlacement",
    "CValidatorLocationShrub",
    "CValidatorLocationType",
    "CValidatorLocationVision",
    "CValidatorPlayer",
    "CValidatorPlayerAlliance",
    "CValidatorPlayerRequirement",
    "CValidatorPlayerTalent",
    "CValidatorPlayerFood",
    "CValidatorPlayerCompare",
    "CValidatorPlayerCompareDifficulty",
    "CValidatorPlayerCompareFoodAvailable",
    "CValidatorPlayerCompareFoodMade",
    "CValidatorPlayerCompareFoodUsed",
    "CValidatorPlayerCompareRace",
    "CValidatorPlayerCompareResource",
    "CValidatorPlayerCompareResult",
    "CValidatorPlayerCompareType",
    "CValidatorUnit",
    "CValidatorUnitInWeaponRange",
    "CValidatorUnitAI",
    "CValidatorUnitCombatAI",
    "CValidatorUnitAlliance",
    "CValidatorUnitAbil",
    "CValidatorUnitBehaviorStackAlias",
    "CValidatorUnitBehaviorState",
    "CValidatorUnitState",
    "CValidatorUnitDetected",
    "CValidatorUnitArmor",
    "CValidatorUnitFilters",
    "CValidatorUnitFlying",
    "CValidatorUnitInventory",
    "CValidatorUnitInventoryIsFull",
    "CValidatorUnitInventoryContainsItem",
    "CValidatorUnitLastDamagePlayer",
    "CValidatorUnitKinetic",
    "CValidatorUnitMissileNullified",
    "CValidatorUnitMover",
    "CValidatorUnitOrder",
    "CValidatorUnitOrderQueue",
    "CValidatorUnitOrderTargetPathable",
    "CValidatorUnitOrderTargetType",
    "CValidatorUnitPathable",
    "CValidatorUnitPathing",
    "CValidatorUnitScanning",
    "CValidatorUnitType",
    "CValidatorUnitWeaponAnimating",
    "CValidatorUnitWeaponFiring",
    "CValidatorUnitWeaponPlane",
    "CValidatorUnitTestWeaponType",
    "CValidatorUnitCompare",
    "CValidatorUnitCompareAIAreaEvalRatio",
    "CValidatorUnitCompareAbilLevel",
    "CValidatorUnitCompareAbilSkillPoint",
    "CValidatorUnitCompareAbilStage",
    "CValidatorUnitCompareAttackPriority",
    "CValidatorUnitCompareBehaviorCount",
    "CValidatorUnitCompareCargo",
    "CValidatorUnitCompareChargeUsed",
    "CValidatorUnitCompareCooldown",
    "CValidatorUnitCompareDamageDealtTime",
    "CValidatorUnitCompareDamageTakenTime",
    "CValidatorUnitCompareDeath",
    "CValidatorUnitCompareDetectRange",
    "CValidatorUnitCompareField",
    "CValidatorUnitCompareKillCount",
    "CValidatorUnitCompareMarkerCount",
    "CValidatorUnitCompareMoverPhase",
    "CValidatorUnitCompareOrderCount",
    "CValidatorUnitCompareOrderTargetRange",
    "CValidatorUnitComparePowerSourceLevel",
    "CValidatorUnitComparePowerUserLevel",
    "CValidatorUnitCompareRallyPointCount",
    "CValidatorUnitCompareResourceContents",
    "CValidatorUnitCompareResourceHarvesters",
    "CValidatorUnitCompareSpeed",
    "CValidatorUnitCompareVeterancyLevel",
    "CValidatorUnitCompareVital",
    "CValidatorUnitCompareVitality",
    "CValidatorUnitCompareHeight",
    "CValidatorCompareTrackedUnitsCount",
    "CValidatorIsUnitTracked"
  ],
  EClassIdCVoiceOver: [
    "CVoiceOver"
  ],
  EClassIdCVoicePack: [
    "CVoicePack"
  ],
  EClassIdCWarChest: [
    "CWarChest"
  ],
  EClassIdCWarChestSeason: [
    "CWarChestSeason"
  ],
  EClassIdCWater: [
    "CWater"
  ],
  EClassIdCWeapon: [
    "CWeapon",
    "CWeaponLegacy",
    "CWeaponStrafe"
  ]
}

let enumData = {}
for(let enumName in enumConfig){
    enumData[enumName] = createEnumClass(enumName,enumConfig[enumName])
}
export default enumData



//todo 
//need to add support of data based ocnstants 
`
    <const id="Small" path="CUnit.Collide.index" value="Land16"/>
    <const id="Burrow" path="CUnit.Collide.index" value="Land1"/>
    <const id="TinyCritter" path="CUnit.Collide.index" value="Land8"/>
    <const id="Swarm" path="CUnit.Collide.index" value="Land4"/>
    <const id="ForceField" path="CUnit.Collide.index" value="Land9"/>
    <const id="Locust" path="CUnit.Collide.index" value="Land11"/>
    <const id="DisruptorPhased" path="CUnit.Collide.index" value="Land15"/>
    <const id="Structure" path="CUnit.Collide.index" value="Land6"/>
    <const id="FlyingImmobile" path="CUnit.Collide.index" value="Air2"/>
    <const id="FlyingEscorts" path="CUnit.Collide.index" value="Air3"/>
    <const id="Ground" path="CUnit.Collide.index" value="Land2"/>
    <const id="LocustForceField" path="CUnit.Collide.index" value="Land12"/>
    <const id="Flying" path="CUnit.Collide.index" value="Air1"/>
    <const id="Colossus" path="CUnit.Collide.index" value="Land5"/>
    <const id="CreepTumor" path="CUnit.Collide.index" value="Land10"/>
    <const id="RoachBurrow" path="CUnit.Collide.index" value="Land7"/>
    <const id="Phased" path="CUnit.Collide.index" value="Land14"/>
    <const id="Larva" path="CUnit.Collide.index" value="Land3"/>
` 

const enumConstants = {
    CUnit: {
        Collide: {
            index: {
                Small: "Land16" // 15
            }
        }
    }
}  
    // <const id="lumber" path="CUnitHero.CostResource.index" value="Custom"/>

//  <const id="$Spell" type="CActorMsgPayloadPtr" value="AnimPlay Spell Spell"/>
//         <On Terms="ActorCreation" Send="$Stand PlayForever,RandomStartOffset"/>

// <const id="ward" path="CAbilEffectInstant.TargetFilters" value="Robotic"/>

// <TargetFilters index="0" value="mechanical;self,enemies,ward,ancient,wall,tree,Missile,debris,UnderConstruction,Dead,Hallucination,Decaying,Raisable,item"/>


    // <const id="divine" path="CEffectDamage.AttributeFactor.index" value="Robotic"/>
    //     <!--AttributeFactor index="divine" value="-0.95"/>
